// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

export const Index: Record<string, any> = {
  "new-york": {
    "hello-world":  {
      name: "hello-world",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/new-york/ui/hello-world.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      source: "",
      meta: undefined,
    }
  },
}
